"""All-competition fixture cache for accurate rest-day calculation.

Loads fixture CSVs generated by ``scripts/ingest_espn_fixtures.py`` (ESPN Site
API data covering Premier League, FA Cup, League Cup, Champions League, Europa
League, Conference League) and provides efficient lookup of the most recent
fixture before a given time for any team.
"""

from __future__ import annotations

import bisect
import csv
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

__all__ = [
    "FixtureRecord",
    "FixtureCache",
    "load_fixture_cache",
    "get_last_fixture_date",
]

# Default location relative to project root
_DEFAULT_DATA_DIR = Path(__file__).resolve().parents[3] / "data" / "espn_fixtures"


@dataclass(frozen=True, slots=True)
class FixtureRecord:
    """A single fixture entry (date + competition)."""

    date: datetime
    competition: str


# team_name -> chronological list of all-competition fixtures
FixtureCache = dict[str, list[FixtureRecord]]


def load_fixture_cache(data_dir: str | Path | None = None) -> FixtureCache:
    """Load all fixture CSVs from the data directory into a unified cache.

    Each team maps to a chronologically sorted list of FixtureRecord entries
    spanning all competitions and all seasons.
    """
    directory = Path(data_dir) if data_dir is not None else _DEFAULT_DATA_DIR
    cache: FixtureCache = {}

    csv_files = sorted(directory.glob("fixtures_*.csv"))
    if not csv_files:
        return cache

    for csv_path in csv_files:
        with open(csv_path, newline="") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                team = row["team"]
                date_str = row["date"]
                competition = row["competition"]

                dt = _parse_date(date_str)
                record = FixtureRecord(date=dt, competition=competition)

                if team not in cache:
                    cache[team] = []
                cache[team].append(record)

    # Sort each team's fixtures chronologically (CSVs are per-season and sorted,
    # but loading multiple seasons can interleave)
    for team in cache:
        cache[team].sort(key=lambda r: r.date)

    return cache


def get_last_fixture_date(
    cache: FixtureCache,
    team: str,
    before: datetime,
) -> datetime | None:
    """Find the most recent fixture date for a team strictly before the given time.

    Uses binary search since fixtures are sorted chronologically. Returns None
    if the team is not in the cache or has no fixtures before the given time.
    """
    fixtures = cache.get(team)
    if not fixtures:
        return None

    # bisect on date: find insertion point for 'before', then take the one before it
    idx = bisect.bisect_left(fixtures, before, key=lambda r: r.date)

    if idx == 0:
        return None

    return fixtures[idx - 1].date


def _parse_date(date_str: str) -> datetime:
    """Parse ISO-format date string from ESPN CSV to timezone-aware datetime."""
    # ESPN format: "2024-08-17T14:00Z"
    cleaned = date_str.rstrip("Z")
    dt = datetime.fromisoformat(cleaned)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    return dt
