"""add paper trades table

Revision ID: 021f43706c10
Revises: 3387940c2f83
Create Date: 2026-04-09 20:51:16.166460

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "021f43706c10"
down_revision = "3387940c2f83"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("market", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("selection", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bookmaker", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("odds", sa.Integer(), nullable=False),
        sa.Column("stake", sa.Float(), nullable=False),
        sa.Column("reasoning", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("bankroll_before", sa.Float(), nullable=False),
        sa.Column("bankroll_after", sa.Float(), nullable=True),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result", sa.Enum("WIN", "LOSS", "PUSH", "VOID", name="traderesult"), nullable=True
        ),
        sa.Column("pnl", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_paper_trades_bookmaker"), "paper_trades", ["bookmaker"], unique=False)
    op.create_index(op.f("ix_paper_trades_event_id"), "paper_trades", ["event_id"], unique=False)
    op.create_index(
        "ix_paper_trades_event_selection", "paper_trades", ["event_id", "selection"], unique=False
    )
    op.create_index(
        "ix_paper_trades_unsettled",
        "paper_trades",
        ["settled_at"],
        unique=False,
        postgresql_where=sa.text("settled_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_paper_trades_unsettled",
        table_name="paper_trades",
        postgresql_where=sa.text("settled_at IS NULL"),
    )
    op.drop_index("ix_paper_trades_event_selection", table_name="paper_trades")
    op.drop_index(op.f("ix_paper_trades_event_id"), table_name="paper_trades")
    op.drop_index(op.f("ix_paper_trades_bookmaker"), table_name="paper_trades")
    op.drop_table("paper_trades")
    # ### end Alembic commands ###
